# Generated by Django 3.2.8 on 2021-10-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('released_date', models.DateField(auto_now_add=True, verbose_name='등록시간')),
                ('ticker', models.ManyToManyField(to='ticker.Ticker', verbose_name='종목명')),
            ],
            options={
                'verbose_name': '뉴스',
                'verbose_name_plural': '뉴스',
            },
        ),
    ]
